### PR TITLE
To Do List

### PR DESCRIPTION
**Pull request by rushemaa**
## To Do list: list structure

In this first milestone, I: 

- Set up a new project with webpack
- Created an index.html file
- Set index.html as a template using the HTML Webpack Plugin
- loaded CSS by Webpack Style/CSS Loader

### CODE REVIEW

**Comment by Alfredbis29** [comment]
Hello @rushemaa  I'm reviewing your Project but I don't know why you still commit on this PR , you are not allowed to push on this PR once being submitted :pray:

**Comment by rushemaa** [comment]
I am really sorry, I won't do it again

**Comment by rushemaa** [comment]
> Hello @rushemaa I'm reviewing your Project but I don't know why you still commit on this PR , you are not allowed to push on this PR once being submitted 🙏

I am really sorry, I won't do it again

**Review by Alfredbis29 — APPROVED** [review]
# STATUS: APPROVED   
 ## Hi @rushemaa 
Your project is complete! There is nothing else to say other than... Great job clap Congratulations! :tada:
 
 TO HIGHLIGHT:
 
 * Your project is professional :white_check_mark:
 * Well structured files :white_check_mark:
 *  Adds validations and write unit tests for all the models. :wink: :white_check_mark:  
 * Good Job :+1: :smile: 
 
 Now you can merge this branch and move on 1st_place_medal: HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :


 
 ## Optional suggestions

- [x] Ensure that the tasks array is sorted in order of the index values for each task before rendering to the DOM. :wink: 
- [x] Update the populateTasks function to include the additional properties added to the tasks array. :+1: 

 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
 
Cheers and Happy coding! :clap:  :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @Alfredbis29 in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
